#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 31, 2019 01:02:20 AM CST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import 订阅端_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    订阅端_support.set_Tk_var()
    top = Toplevel1 (root)
    订阅端_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    订阅端_support.set_Tk_var()
    top = Toplevel1 (w)
    订阅端_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("778x277+216+239")
        top.title("订阅端")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Labelframe1 = tk.LabelFrame(top)
        self.Labelframe1.place(relx=0.026, rely=0.072, relheight=0.921
                , relwidth=0.411)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''订阅设置''')
        self.Labelframe1.configure(background="#d891a1")
        self.Labelframe1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1.configure(highlightcolor="black")
        self.Labelframe1.configure(width=320)

        self.TLabel1 = ttk.Label(self.Labelframe1)
        self.TLabel1.place(relx=0.031, rely=0.118, height=21, width=64
                , bordermode='ignore')
        self.TLabel1.configure(background="#383dd8")
        self.TLabel1.configure(foreground="#ffffff")
        self.TLabel1.configure(font="TkDefaultFont")
        self.TLabel1.configure(relief="flat")
        self.TLabel1.configure(text='''服务器地址''')

        self.TLabel2 = ttk.Label(self.Labelframe1)
        self.TLabel2.place(relx=0.031, rely=0.235, height=21, width=40
                , bordermode='ignore')
        self.TLabel2.configure(background="#383dd8")
        self.TLabel2.configure(foreground="#ffffff")
        self.TLabel2.configure(font="TkDefaultFont")
        self.TLabel2.configure(relief="flat")
        self.TLabel2.configure(text='''端口号''')

        self.TEntry_port = ttk.Entry(self.Labelframe1)
        self.TEntry_port.place(relx=0.25, rely=0.235, relheight=0.09
                , relwidth=0.113, bordermode='ignore')
        self.TEntry_port.configure(textvariable=订阅端_support.vartext_port)
        self.TEntry_port.configure(takefocus="")
        self.TEntry_port.configure(cursor="ibeam")

        self.TEntry_username = ttk.Entry(self.Labelframe1)
        self.TEntry_username.place(relx=0.25, rely=0.51, relheight=0.09
                , relwidth=0.456, bordermode='ignore')
        self.TEntry_username.configure(textvariable=订阅端_support.vartext_username)
        self.TEntry_username.configure(takefocus="")
        self.TEntry_username.configure(cursor="ibeam")

        self.TEntry_password = ttk.Entry(self.Labelframe1)
        self.TEntry_password.place(relx=0.25, rely=0.627, relheight=0.09
                , relwidth=0.456, bordermode='ignore')
        self.TEntry_password.configure(show="*")
        self.TEntry_password.configure(textvariable=订阅端_support.vartext_password)
        self.TEntry_password.configure(takefocus="")
        self.TEntry_password.configure(cursor="ibeam")

        self.TLabel3 = ttk.Label(self.Labelframe1)
        self.TLabel3.place(relx=0.031, rely=0.51, height=21, width=40
                , bordermode='ignore')
        self.TLabel3.configure(background="#5c4ed8")
        self.TLabel3.configure(foreground="#ffffff")
        self.TLabel3.configure(font="TkDefaultFont")
        self.TLabel3.configure(relief="flat")
        self.TLabel3.configure(text='''用户名''')

        self.TLabel4 = ttk.Label(self.Labelframe1)
        self.TLabel4.place(relx=0.031, rely=0.627, height=21, width=28
                , bordermode='ignore')
        self.TLabel4.configure(background="#6961d8")
        self.TLabel4.configure(foreground="#ffffff")
        self.TLabel4.configure(font="TkDefaultFont")
        self.TLabel4.configure(relief="flat")
        self.TLabel4.configure(text='''密码''')

        self.TButton1 = ttk.Button(self.Labelframe1)
        self.TButton1.place(relx=0.063, rely=0.863, height=27, width=87
                , bordermode='ignore')
        self.TButton1.configure(command=订阅端_support.btn_开始订阅被单击)
        self.TButton1.configure(takefocus="")
        self.TButton1.configure(text='''开始订阅''')

        self.TButton2 = ttk.Button(self.Labelframe1)
        self.TButton2.place(relx=0.469, rely=0.863, height=27, width=87
                , bordermode='ignore')
        self.TButton2.configure(command=订阅端_support.btn_停止订阅被单击)
        self.TButton2.configure(takefocus="")
        self.TButton2.configure(text='''停止订阅''')

        self.TLabel5 = ttk.Label(self.Labelframe1)
        self.TLabel5.place(relx=0.031, rely=0.392, height=21, width=52
                , bordermode='ignore')
        self.TLabel5.configure(background="#4641d8")
        self.TLabel5.configure(foreground="#ffffff")
        self.TLabel5.configure(font="TkDefaultFont")
        self.TLabel5.configure(relief="flat")
        self.TLabel5.configure(text='''服务质量''')

        self.TCombobox_qos = ttk.Combobox(self.Labelframe1)
        self.TCombobox_qos.place(relx=0.25, rely=0.392, relheight=0.09
                , relwidth=0.197, bordermode='ignore')
        self.value_list = [0,1,2,]
        self.TCombobox_qos.configure(values=self.value_list)
        self.TCombobox_qos.configure(textvariable=订阅端_support.vartext_qos)
        self.TCombobox_qos.configure(takefocus="")

        self.TCombobox_ip = ttk.Combobox(self.Labelframe1)
        self.TCombobox_ip.place(relx=0.25, rely=0.118, relheight=0.09
                , relwidth=0.447, bordermode='ignore')
        self.value_list = ['47.93.30.53',]
        self.TCombobox_ip.configure(values=self.value_list)
        self.TCombobox_ip.configure(textvariable=订阅端_support.vartext_ip)
        self.TCombobox_ip.configure(takefocus="")

        self.TLabel6 = ttk.Label(self.Labelframe1)
        self.TLabel6.place(relx=0.031, rely=0.745, height=21, width=52
                , bordermode='ignore')
        self.TLabel6.configure(background="#6961d8")
        self.TLabel6.configure(foreground="#ffffff")
        self.TLabel6.configure(font="TkDefaultFont")
        self.TLabel6.configure(relief="flat")
        self.TLabel6.configure(text='''订阅主题''')

        self.TCombobox_topic = ttk.Combobox(self.Labelframe1)
        self.TCombobox_topic.place(relx=0.25, rely=0.745, relheight=0.102
                , relwidth=0.447, bordermode='ignore')
        self.value_list = ['/data/#','/data/message','/data/alarm','/data/notify',]
        self.TCombobox_topic.configure(values=self.value_list)
        self.TCombobox_topic.configure(textvariable=订阅端_support.vartext_topic)
        self.TCombobox_topic.configure(takefocus="")

        self.Scrolledtext1 = ScrolledText(top)
        self.Scrolledtext1.place(relx=0.437, rely=0.072, relheight=0.921
                , relwidth=0.541)
        self.Scrolledtext1.configure(background="white")
        self.Scrolledtext1.configure(font="TkTextFont")
        self.Scrolledtext1.configure(foreground="black")
        self.Scrolledtext1.configure(highlightbackground="#d9d9d9")
        self.Scrolledtext1.configure(highlightcolor="black")
        self.Scrolledtext1.configure(insertbackground="black")
        self.Scrolledtext1.configure(insertborderwidth="3")
        self.Scrolledtext1.configure(selectbackground="#c4c4c4")
        self.Scrolledtext1.configure(selectforeground="black")
        self.Scrolledtext1.configure(width=10)
        self.Scrolledtext1.configure(wrap="none")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.sub_menu = tk.Menu(top,tearoff=0)
        self.menubar.add_cascade(menu=self.sub_menu,
                activebackground="#ececec",
                activeforeground="#000000",
                background="#d9d9d9",
                font="TkMenuFont",
                foreground="#000000",
                label="settings")
        self.sub_menu1 = tk.Menu(top,tearoff=0)
        self.sub_menu.add_cascade(menu=self.sub_menu1,
                activebackground="#ececec",
                activeforeground="#000000",
                background="#d9d9d9",
                font="TkMenuFont",
                foreground="#000000",
                label="language")
        self.sub_menu1.add_command(
                activebackground="#ececec",
                activeforeground="#000000",
                background="#d9d9d9",
                font="TkMenuFont",
                foreground="#000000",
                label="English")
        self.sub_menu1.add_command(
                activebackground="#ececec",
                activeforeground="#000000",
                background="#d9d9d9",
                font="TkMenuFont",
                foreground="#000000",
                label="中文")
        self.sub_menu12 = tk.Menu(top,tearoff=0)
        self.menubar.add_cascade(menu=self.sub_menu12,
                activebackground="#ececec",
                activeforeground="#000000",
                background="#d9d9d9",
                font="TkMenuFont",
                foreground="#000000",
                label="about")
        self.sub_menu12.add_command(
                activebackground="#ececec",
                activeforeground="#000000",
                background="#d9d9d9",
                font="TkMenuFont",
                foreground="#000000",
                label="version")

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''

    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)

        #self.configure(yscrollcommand=_autoscroll(vsb),
        #    xscrollcommand=_autoscroll(hsb))
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))

        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')

        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)

        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        else:
            methods = tk.Pack.__dict__.keys() + tk.Grid.__dict__.keys() \
                  + tk.Place.__dict__.keys()

        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledText(AutoScroll, tk.Text):
    '''A standard Tkinter Text widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Text.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')

if __name__ == '__main__':
    vp_start_gui()





